spring:
  profiles: h2
  h2:
    console:
      enabled: true
      path: /h2-console

webclient.h2-console-port: 8081


---

spring:
  profiles: mysql
  r2dbc:
    url: r2dbc:mysql://localhost:3306/jpa_study?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql_local