spring:
  profiles: local

---

spring:
  profiles: mysql-db
  r2dbc:
    url: r2dbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf8
    username: glenn
    password: glenn1234

spring.thymeleaf.reactive.max-chunk-size: 8192

logging.level.org.springframework.data.r2dbc: DEBUG